[project]
name = "geo-tfidf"
version = "0.1.0"
description = "Demo Generative Engine Optimisation with classical NLP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.8.5",
    "duckdb>=1.5.3",
    "fastapi>=0.136.3",
    "ipython>=9.13.0",
    "jupyter>=1.1.1",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "plotnine>=0.15.4",
    "scikit-learn>=1.8.0",
    "wordcloud>=1.9.6",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
